Removed editorconfig pyc files from git. Added checking if on release branch to pre-commit hook.

diff --git a/.git_template/hooks/pre-commit b/.git_template/hooks/pre-commit
--- a/.git_template/hooks/pre-commit
+++ b/.git_template/hooks/pre-commit
@@ -43,5 +43,26 @@ exec < /dev/tty
 		fi
 	}
 
+	#make sure we want to commit to the release branch if that's where we are.
+	checkRelease (){
+		BRANCH="$(git symbolic-ref HEAD 2>/dev/null)" || BRANCH="(unnamed branch)"
+		BRANCH=${BRANCH##refs/heads/}
+		if [ $BRANCH = 'release' ]; then
+			while true; do
+				echo -ne '\033[38;5;57mAre you sure you wish to commit to the release branch? [y,n]\033[39m'; read
+				case $REPLY in
+				[Yy])
+					exit 0
+					;;
+				[NnQq])
+					echo -e '\033[38;5;49mGit Commit aborted.\033[39m'
+					exit 1
+					;;
+				esac
+			done
+		fi
+	}
+
 # Call our hook functions
 	jwtodoCheck
+	checkRelease
